# SPDX-License-Identifier: MIT
"""Assemble deterministic manifests, workbooks, PDFs, and handoff archives.

Stage
-----
Packaging runs after scientific tables and figures are persisted and before
final independent acceptance.

Inputs
------
Inputs are completed derivative artifacts, the public code tree, and explicit
file-selection lists.

Outputs
-------
Functions write combined PDFs, Excel workbooks, copied paper items, ZIP files,
or return checksum manifest tables.

Side Effects
------------
Creates directories and writes derivative package files; source inputs are read
only.

Invariants
----------
Ordering is deterministic, manifests hash actual bytes, bytecode/cache files
are excluded, and handoff ZIP CRC is verified before return.

Lane
----
Portable derivative packaging and transfer lane.
"""

from __future__ import annotations

import shutil
import zipfile
from pathlib import Path
from typing import Iterable

import pandas as pd
from pypdf import PdfReader, PdfWriter

from .utilities import relative_posix, sha256_file


def combine_pdfs(sources: Iterable[Path], destination: Path) -> tuple[Path | None, list[str]]:
    """Combine readable, non-empty PDFs in deterministic order.

    Parameters
    ----------
    sources : iterable of pathlib.Path
        Candidate PDFs; duplicates, missing files, empty files, and unreadable
        PDFs are skipped.
    destination : pathlib.Path
        Combined PDF destination.

    Returns
    -------
    combined : pathlib.Path or None
        Destination when at least one source was included, otherwise ``None``.
    included : list of str
        Included source paths in append order.

    Side Effects
    ------------
    Writes ``destination`` only when one or more readable pages are available.
    """
    writer = PdfWriter()
    included: list[str] = []
    for source in sorted({Path(path) for path in sources}, key=lambda path: str(path).lower()):
        if not source.exists() or source.stat().st_size == 0:
            continue
        try:
            reader = PdfReader(str(source))
            if not reader.pages:
                continue
            writer.append(reader)
            included.append(str(source))
        except Exception:
            continue
    if not included:
        return None, []
    destination.parent.mkdir(parents=True, exist_ok=True)
    with destination.open("wb") as handle:
        writer.write(handle)
    return destination, included


def summary_workbook(sheets: dict[str, pd.DataFrame], destination: Path) -> Path:
    """Write named tables to an Excel summary workbook.

    Parameters
    ----------
    sheets : dict of str to pandas.DataFrame
        Desired sheet names and tables in insertion order.
    destination : pathlib.Path
        XLSX output path.

    Returns
    -------
    pathlib.Path
        Written workbook path.

    Side Effects
    ------------
    Creates the parent directory and writes an ``openpyxl`` workbook.
    """
    destination.parent.mkdir(parents=True, exist_ok=True)
    with pd.ExcelWriter(destination, engine="openpyxl") as writer:
        for name, frame in sheets.items():
            safe_name = name[:31].replace("/", "_").replace("\\", "_")
            frame.to_excel(writer, sheet_name=safe_name, index=False)
    return destination


def output_manifest(root: Path, excluded_names: set[str] | None = None) -> pd.DataFrame:
    """Inventory derivative files beneath a run root.

    Parameters
    ----------
    root : pathlib.Path
        Directory to inventory recursively.
    excluded_names : set of str, optional
        Basenames omitted to avoid self-reference or transient artifacts.

    Returns
    -------
    pandas.DataFrame
        Relative paths, byte sizes, and SHA-256 digests in deterministic order.
    """
    excluded_names = excluded_names or set()
    rows = []
    for path in sorted(root.rglob("*"), key=lambda item: str(item).lower()):
        if not path.is_file() or path.name in excluded_names:
            continue
        rows.append({
            "relative_path": relative_posix(path, root),
            "bytes": path.stat().st_size,
            "sha256": sha256_file(path),
        })
    return pd.DataFrame(rows)


def code_manifest(code_root: Path) -> pd.DataFrame:
    """Inventory source-tree files while excluding generated bytecode.

    Parameters
    ----------
    code_root : pathlib.Path
        Public source-tree root.

    Returns
    -------
    pandas.DataFrame
        Relative paths, byte sizes, and SHA-256 digests.
    """
    rows = []
    for path in sorted(code_root.rglob("*"), key=lambda item: str(item).lower()):
        if not path.is_file() or "__pycache__" in path.parts or path.suffix == ".pyc":
            continue
        rows.append({
            "relative_path": relative_posix(path, code_root),
            "bytes": path.stat().st_size,
            "sha256": sha256_file(path),
        })
    return pd.DataFrame(rows)


def compact_handoff_zip(
    run_root: Path,
    code_root: Path,
    destination: Path,
    include_files: Iterable[Path],
) -> tuple[Path, pd.DataFrame]:
    """Create a compact evidence package without large governed authorities.

    Parameters
    ----------
    run_root : pathlib.Path
        Derivative run root used for ``run/`` archive names.
    code_root : pathlib.Path
        Code root copied under ``code/``.
    destination : pathlib.Path
        ZIP output path.
    include_files : iterable of pathlib.Path
        Explicit run, code, or support artifacts to include.

    Returns
    -------
    destination : pathlib.Path
        Validated ZIP path.
    manifest : pandas.DataFrame
        Archive members, source paths, and source-file SHA-256 digests.

    Raises
    ------
    RuntimeError
        If ZIP CRC validation identifies a corrupt member.

    Side Effects
    ------------
    Writes and then reopens the ZIP for validation.
    """
    destination.parent.mkdir(parents=True, exist_ok=True)
    selected: list[tuple[Path, str]] = []
    for path in include_files:
        path = Path(path)
        if path.exists() and path.is_file():
            try:
                arcname = "run/" + relative_posix(path, run_root)
            except ValueError:
                try:
                    arcname = "code/" + relative_posix(path, code_root)
                except ValueError:
                    arcname = "support/" + path.name
            selected.append((path, arcname))
    for path in code_root.rglob("*"):
        if path.is_file() and "__pycache__" not in path.parts and path.suffix != ".pyc":
            selected.append((path, "code/" + relative_posix(path, code_root)))
    # Archive names are the deduplication key so explicit selections and the
    # recursive code pass cannot create duplicate ZIP members.
    unique = {arcname: path for path, arcname in selected}
    with zipfile.ZipFile(destination, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
        for arcname, path in sorted(unique.items()):
            archive.write(path, arcname)
    with zipfile.ZipFile(destination, "r") as archive:
        bad = archive.testzip()
        if bad is not None:
            raise RuntimeError(f"Handoff ZIP CRC failure at {bad}")
        names = archive.namelist()
    manifest = pd.DataFrame([
        {"archive_member": name, "source_path": str(unique[name]), "sha256": sha256_file(unique[name])}
        for name in names
    ])
    return destination, manifest


def copy_paper_item(source: Path, destination_dir: Path) -> Path:
    """Copy one artifact into the paper-facing directory with metadata.

    Parameters
    ----------
    source : pathlib.Path
        Existing source artifact.
    destination_dir : pathlib.Path
        Target directory.

    Returns
    -------
    pathlib.Path
        Copied artifact path.

    Side Effects
    ------------
    Creates the directory and copies file metadata with ``shutil.copy2``.
    """
    destination_dir.mkdir(parents=True, exist_ok=True)
    target = destination_dir / source.name
    shutil.copy2(source, target)
    return target
